# Generated by Django 3.2.12 on 2023-01-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bogdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=100)),
                ('blogimage', models.ImageField(upload_to='images/')),
                ('blogdesc', models.CharField(max_length=500)),
                ('blogdate', models.DateTimeField(auto_now_add=True)),
                ('blogcontact', models.IntegerField()),
            ],
        ),
    ]
