# Generated by Django 3.2.12 on 2023-01-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_bogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogdetail',
            name='blogdesc',
            field=models.CharField(max_length=1000),
        ),
    ]
